### ISSUE TITLE
When plotting profiles, the legend repeats the first entry

### ISSUE THREAD

**Issue by MoniaNielsen** [abTEM/abTEM#138]
Hello,
When trying to plot multiple lines, the legend only uses the first entry. And I don't know how to fix this.

I just used the example of potentials in the walkthrough (see below).

```
import abtem
import matplotlib.pyplot as plt
from abtem.parametrizations import LobatoParametrization
from ase.io import read

symbols = ["C", "N", "Si", "Au", "U"]

parametrization = LobatoParametrization()

potentials = parametrization.line_profiles(symbols, cutoff=2, name="potential")
scattering_factor = parametrization.line_profiles(
    symbols, cutoff=3, name="scattering_factor"
)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
visualization = potentials.show(ax=ax1)
visualization.set_ylim([0, 2e3])

scattering_factor.show(legend=True, ax=ax2);
```

![Skærmbillede 2024-01-29 100709](https://github.com/abTEM/abTEM/assets/158033493/e9d38a17-039d-471b-a53e-1f3151082691)

I just got a new computer, so it should not be affected by other/old anaconda environments. I assume that it is a package thing... 
- Conda is updated to the latest version: 23.11.0
- I installed a completely new environment
- I am using python 3.10.12 with abTEM 1.0.4 (I tried to install both from conda-forge and pip, same issue)
- I have tried different kernels

No matter what I do, the legend issue remains and I don't know what else to try... any help would be very much appreciated.

**Comment by TomaSusi** [comment]
Hi, and apologies for the delayed response! I am not able to reproduce the issue with your script using abTEM 1.0.4, could you check again, maybe this was fixed already?

<img width="999" alt="image" src="https://github.com/abTEM/abTEM/assets/66075496/adcfa258-e8b4-4b07-b38a-f48a70601bc7">

**Comment by MoniaNielsen** [comment]
Hi,
I still have the issue, and I have the same issue on both a Mac and pc. 
In both cases, I am installing the abTEM package in a new environment, where the Mac is old and I have other environments installed (don't know if the new environment is affected by using the same kernel as the other environments) and the PC is a new work computer, both having the same issue.

**Comment by TomaSusi** [comment]
Curious… in a Python prompt or a Jupyter cell, what do you get when you give the commands:

‘’’import abtem
abtem.__file__’’’

Does the printed path correspond to the right directory?

If you’re using Jupyter, what is the kernel that is active?

Can you give the full list of terminal commands you use to install and start your abTEM session in Jupyter?

**Comment by MoniaNielsen** [comment]
I can run the following without any error:
`import abtem`

But I actually can't run the following in a Jupyter cell to get the path to the abTEM package:
`import abtem`
`abtem.file`

I get an AttributeError: module 'abtem' has no attribute 'file'

I tried with another package, and I get the same error as above. Is there a difference between getting the path to a package in Jupyter Notebook on a mac or pc?

The active kernel when using Jupyter Notebook is: Python 3 (ipykernel)

**Install abTEM in a new environment**
1. Check conda is installed (*I can't remember exactly what the previous version was)
`$conda V`
`conda 22.11.0`

2. Check conda is up to date (*23.11.0 is the newest version)
`$conda update conda`
`conda 23.11.0`

3. Create a virtual environment using python 3.10.12 (*I also tried with the newest python version)
`$conda create -n my-env python=3.10.12 anaconda`

4. Activate my-env
`$conda activate my-env`

5. Install abTEM with conda (*I also tried with `$pip install abtem`)
`$conda install -c conda-forge abtem`

6. Make the environment accessible in Jupyter Notebook. 
6.1 Navitage to the base environment
`$conda deactivate`

6.2. Install the following in the base
`$conda install nb_conda_kernels`

6.3. Activate environment again
`$conda activate my-env`

6.4. Install the following
`$conda install ipykernel`

6.5 Navitage to the base environment when finishing
`$conda deactivate`

**New session - Open Anaconda prompt**
7.1. Activate my-env
`$conda activate my-env`

7.2. Navigate to folder
`$cd path/to/folder`

9. Open Jupyter Notebook
`$jupyter notebook`

**Comment by TomaSusi** [comment]
> I can run the following without any error: `import abtem`
> 
> But I actually can't run the following in a Jupyter cell to get the path to the abTEM package: `import abtem` `abtem.file`
> 
> I get an AttributeError: module 'abtem' has no attribute 'file'

It's not `abtem.file` but `abtem.__file__`.

**Comment by MoniaNielsen** [comment]
This printed path is the following:
Mac: '/Users/user/opt/anaconda3/envs/abTEM/lib/python3.10/site-packages/abtem/__init__.py'
PC: 'C:\\Users\\user\\AppData\\Local\\anaconda3\\env\\abTEM\\lib\\site-packages\abtem\\__init__.py'

When you ask if it corresponds to the right directory, do you mean the directory where abTEM is installed or the directory from which I am trying to run the potential example from above?

I didn't change anything during the installment and I guess abTEM is just installed in the default position under site-packages?

I have now matched the name of my kernel with my conda environment (now both called abTEM), which didn't help as I still have the same legend issue. But I don't know if I might have overwritten something from before by not matching the name to the kernel to the name of the environment?

**Comment by TomaSusi** [comment]
By directory I meant the directory from which abTEM is loaded. In this instance it is a conda environment called "abTEM" – which is not the same as "my-env". But if you say you have now installed the correct environment kernel to Jupyter and the problem persists, then that's not the culprit either. We'll try to look into this more.

**Comment by jacobjma** [comment]
Could you check whether this is fixed for you in `1.0.5`. It is a somewhat strange issue, I was also not able to reproduce it in `1.0.4`.

**Comment by MoniaNielsen** [comment]
I still have the same issue when running abTEM version 1.0.5. - Do I need to update before running?

In the meantime, I got it working by installing abTEM version 1.0.4 with python 3.10.12. - Don't know if this help...?

**Comment by jacobjma** [comment]
The python version should not make a difference. Can you run this in a notebook and report the output?
```python
dir(abtem.visualize.visualizations)
```
